### ISSUE TITLE
webViewcell加载淘宝商品详情页的url获取不到高度呢，循环加载高度一致是650

### ISSUE THREAD

**Issue by imdp6** [alflix/EasyWebView#1]
http:\/\/mdetail.tmall.com\/templates\/pages\/desc?id=604372762402

**Comment by imdp6** [comment]
<img width="291" alt="Screen Shot 2019-12-26 at 4 51 26 PM" src="https://user-images.githubusercontent.com/28843198/71468134-fa6fdc00-27ff-11ea-8744-554c746555fd.png">
打印高度是这样一直循环

**Comment by alflix** [comment]
感谢反馈。会尝试修复～

**Comment by imdp6** [comment]
不用谢，哈哈。这样的链接http:\/\/mdetail.tmall.com\/templates\/pages\/desc?id=604372762402也是那样。我尝试找原因，没找到。

**Comment by imdp6** [comment]
用你的WebViewController就没这个问题

**Comment by alflix** [comment]
在 heightChangeObserve 回调中，使用 `tableView.beginUpdates()  tableView.endUpdates()` 取代 `tableView.reloadData()` 即可。

https://github.com/alflix/EasyWebView/commit/fc7a4233acc48072d784ee450f9cc4456591f7c3#diff-8cdf2d2649f56b498160f27ecc723766L52

**Comment by imdp6** [comment]
🐂
